// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/KScaesar/jubo-homework/backend/application"
	"github.com/KScaesar/jubo-homework/backend/configs"
	"github.com/KScaesar/jubo-homework/backend/infra"
	"github.com/KScaesar/jubo-homework/backend/rest"
	"github.com/KScaesar/jubo-homework/backend/util/database"
	"github.com/gin-gonic/gin"
)

// Injectors from injector.go:

func NewHttpServer(cfg *configs.ProjectConfig) (*gin.Engine, error) {
	dbConfig := cfg.Pgsql
	wrapperGorm, err := database.NewGormPgsql(dbConfig)
	if err != nil {
		return nil, err
	}
	iocApp, err := NewApp(cfg, wrapperGorm)
	if err != nil {
		return nil, err
	}
	patientService := iocApp.PatientService
	patientHandler := rest.NewPatientHandler(patientService)
	engine := rest.RegisterRouter(cfg, patientHandler)
	return engine, nil
}

func NewApp(cfg *configs.ProjectConfig, db *database.WrapperGorm) (*App, error) {
	patientRepository := infra.NewPatientRepository(db)
	patientUseCase := application.NewPatientUseCase(patientRepository)
	iocApp := &App{
		PatientService: patientUseCase,
	}
	return iocApp, nil
}
