version: "3.4"

services:
  jubo-rdb:
    image: postgres:13.4
    container_name: jubo-rdb
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=caesar
      - POSTGRES_PASSWORD=1234
    ports:
      - "15432:5432"
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - data:/var/lib/postgresql/data

  jubo-server:
     image: "x246libra/jubo-homework-backend:v1.0"
     container_name: jubo-server
     restart: always
     environment:
       - WorkDir=/app
       - ConfigPath=./configs/container.yaml
     ports:
       - "8888:8888"
#     volumes:
#       - .backend/configs:/app/backend/configs
     depends_on:
       - jubo-rdb

  jubo-web:
     image: "x246libra/jubo-homework-frontend:v1.0"
     container_name: jubo-web
     restart: always
     environment:
       - NODE_ENV=production
       - PORT=3001
     ports:
       - "3001:3001"
#     volumes:
#       - .frontend/.env.production:/app/.env.production
     depends_on:
       - jubo-server

volumes:
  data:
    name: jubo-rdb-data
